# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XlUQLBKso4En21I4bV9ImcUtIsGJy9mG
"""

data={}

import ast
import pandas as pd

train_data=pd.read_excel("ipc_data 120-309.xlsx")
Off = train_data["Offence"]

punish = train_data["Punishment"]

train_data_1= train_data['Section']
train_data_1 = train_data_1.apply(lambda x: ast.literal_eval(x))

Sec_1= train_data_1

for x in range(0,50):
  data[Sec_1[x][0]]=[Off[x],punish[x]]



def data_retrival(code):
  detail = []
  punishment = []
  for i in code:  
    detail.append(data[i][0])
    punishment.append(data[i][1]);
  return detail,punishment



